<?php
/*
Plugin Name: UFCLAS Matlab Upload
Plugin URI: https://it.clas.ufl.edu/
Description: Imports a zip file of HTML and images generated by MATLAB and creates a new page
Version: 0.0.0
Author: Priscilla Chapman (CLAS IT)
Author URI: https://it.clas.ufl.edu/
License: GPL2
Build Date: 20170411
*/

define('UFCLAS_MATLAB_PLUGIN_DIR', plugin_dir_path( __FILE__ )); 

/**
 * Add menu item to Settings in the dashboard menu
 * @since 0.0.0
 */
function ufclas_matlab_register_menu(){
	add_options_page('MATLAB Import', 'MATLAB Import', 'manage_options', 'ufclas-matlab-settings', 'ufclas_matlab_page');
}
add_action('admin_menu', 'ufclas_matlab_register_menu');

function ufclas_matlab_scripts_styles(){
	wp_enqueue_media();
}
add_action('admin_enqueue_scripts', 'ufclas_matlab_scripts_styles');

function ufclas_matlab_page(){
	?>
	<div class="wrap">
		
		<h1><?php _e('MATLAB Importer', 'ufclas-matlab'); ?></h1>
		
		<?php 
		// Ensure that the user has permission to upload
		if ( current_user_can( 'upload_files' ) ): 
			
			// Process the submitted form data
			ufclas_matlab_handle_upload(); 
		?>
		
		<form id="ufclas-matlab-upload" class="" method="post" enctype="multipart/form-data">
			<label for="upload" class="screen-reader-text"><?php _e( 'Choose a file:' ); ?></label><br />
			<input type="file" id="upload" name="import" />
			<?php wp_nonce_field('ufclas-matlab-upload', '_wpnonce_ufclas_matlab_upload' ); ?>
			<?php submit_button( __( 'Upload', 'ufclas-matlab' ), 'primary', 'submit' ); ?>
		</form>
		
		<?php endif; ?>
		
	</div>
	<?php
}

function ufclas_matlab_handle_upload(){
	if ( empty($_FILES) ){
		return;
	}
	
	// Test whether the request includes a valid nonce
	check_admin_referer('ufclas-matlab-upload', '_wpnonce_ufclas_matlab_upload');
	
	// Make sure we have credentials before trying to access the filesystem
	$access_type = get_filesystem_method();
	
	if ( $access_type != 'direct' ){
		// No write access, warn the user with a notice
		add_action( 'admin_notices', 'ufclas_matlab_admin_notice_warning' );
	}
	else {
		$creds = request_filesystem_credentials( admin_url(), '', false, false, array());
		
		// Initialize the API
		if ( ! WP_Filesystem( $creds ) ) {
			return;
		}
		
		global $wp_filesystem;
		
		$uploaded_file = $_FILES['import'];
		$overrides = array( 'test_form' => false, 'test_type' => false );
		$file = wp_handle_upload($uploaded_file, $overrides);

		if ( isset($file['error']) ){
			wp_die( $file['error'] );
		}
		
		// Get the remote system absolute path
		$plugin_path = str_replace(ABSPATH, $wp_filesystem->abspath(), UFCLAS_MATLAB_PLUGIN_DIR);
		$export_path = $plugin_path . 'export/';
		$import_path = $export_path . 'html/';
		
		$wp_filesystem->delete( $import_path, true );
				
		if ( $result = unzip_file( $file['file'], $export_path ) !== true ){
			wp_die( __('Error: could not unzip file. Try again.', 'ufclas-matlab') );
		}
		
		// Construct the object array
		$object = array(
			'post_title' => basename($file['file']),
			'post_content' => $file['url'],
			'post_mime_type' => $file['type'],
			'guid' => $file['url'],
			'context' => 'import',
			'post_status' => 'private'
		);
		
		// Save the data in the posts table
		$upload_id = wp_insert_attachment( $object, $file['file'] );
		
		$dirlist = $wp_filesystem->dirlist( $import_path, false, true );
		$exported_files = array('html' => '', 'images' => array() );
		
		foreach ( $dirlist as $file_name => $file_data ){
			if ( $file_data['type'] == 'f' ){
				
				$name = $file_data['name'];
				
				if ( substr( $name, -5 ) == '.html' ){
					$exported_files['html'] = $name;
				}
				elseif ( substr( $name, -4 ) == '.png' ) {
					$exported_files['images'][] = $name;
				}
			}
		}
		
		$html_path = $import_path . '/' . $exported_files['html'];
		$html_content = $wp_filesystem->get_contents( $html_path );
		
		$dom = new DOMDocument();
		$dom->loadHTML($html_content);
		$node_list = $dom->getElementsByTagName('div');
		$new_dom = new DOMDocument();
		$new_dom->formatOutput = true;
		$new_div = $new_dom->createElement('div');
		$new_div->setAttribute( 'id', 'matlab-import' );
		$new_div->appendChild( $new_dom->importNode($node_list->item(0), true) );
		$new_dom->appendChild( $new_div );

		$post_content = $new_dom->saveHTML();
		
		$html_page_id = wp_insert_post( array(
			'post_title' => $exported_files['html'],
			'post_content' => $post_content,
			'post_type' => 'page',
			'post_author' => get_current_user_id(),
			'post_status' => 'publish'
		) );
		
		foreach ( $exported_files['images'] as $image ){
			$image_path = $import_path . '/' . $image;
			$image_type = wp_check_filetype( basename( $image_path ) );
			$image_upload_dir = wp_upload_dir();
			$image_upload_path = $image_upload_dir['path'] . '/' . $image;
			$image_upload_url = $image_upload_dir['url'] . '/' . $image;
			
			$wp_filesystem->move($image_path, $image_upload_path, true );
			
			$attachment = array(
				'post_title' => preg_replace( '/\.[^.]+$/', '', $image ),
				'post_content' => '',
				'post_mime_type' => $image_type['type'],
				'post_status' => 'inherit',
				'guid' => $image_upload_url
			);
			
			require_once( ABSPATH . 'wp-admin/includes/image.php' );
			
			$attach_id = wp_insert_attachment( $attachment, $image_upload_path, $html_page_id );
			$attach_data = wp_generate_attachment_metadata( $attach_id, $image_upload_path );
			wp_update_attachment_metadata( $attach_id, $attach_data );
			
			$image_url = wp_get_attachment_url( $attach_id, 'full' );
			
			$post_content = str_replace( $image, $image_upload_url, $post_content );
		}
		
		wp_update_post( array( 'ID' => $html_page_id, 'post_content' => $post_content ) );
		wp_delete_attachment( $upload_id );
		$wp_filesystem->delete( $import_path, true );
		
		
	}
}

function ufclas_matlab_admin_notice_warning(){
	?>
    <div class="notice notice-warning is-dismissible">
        <p><?php _e( 'You do not have access to modify files.', 'ufclas-matlab' ); ?></p>
    </div>
    <?php
}